project_id = "riink"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "http://localhost:3000/auth/callback",
  "http://127.0.0.1:3000/auth/callback",
]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.email.template.confirmation]
subject = "Confirm your Riink email"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.recovery]
subject = "Reset your Riink password"
content_path = "./supabase/templates/recovery.html"

[auth.email.template.invite]
subject = "You are invited to Riink"
content_path = "./supabase/templates/invite.html"

[auth.email.template.magic_link]
subject = "Your secure Riink sign in link"
content_path = "./supabase/templates/magic-link.html"

[auth.email.template.email_change]
subject = "Confirm your new Riink email"
content_path = "./supabase/templates/email-change.html"

[auth.email.template.reauthentication]
subject = "Your Riink verification code"
content_path = "./supabase/templates/reauthentication.html"
